language: objective-c
osx_image: xcode9.4
xcode_workspace: DuolingoExample.xcworkspace

before_install:
   - gem install cocoapods
   - pod install

script: 
   - xcodebuild test -workspace DuolingoExample.xcworkspace -scheme "DuolingoExample" -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest'
